version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
      - ENABLE_MODULES=text2vec-transformers
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
    volumes:
      - ./weaviate_data:/var/lib/weaviate

  rag-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - weaviate

#run the command `docker-compose up --build`


#and then start the compose `docker-compose up -d`
